let LESSONS={subjects:[]};let currentSubject=null;let currentLesson=null;let currentBlock=0;
const STORAGE_KEY='studyhub.lessons.progress.v1';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function loadProgress(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}catch(e){return {}}}
function saveProgress(p){localStorage.setItem(STORAGE_KEY,JSON.stringify(p))}
function lessonState(id){const p=loadProgress();return p[id]||{block:0,completed:false,answers:{}}}
function setLessonState(id,patch){const p=loadProgress();p[id]={...lessonState(id),...patch};saveProgress(p)}
async function init(){try{const r=await fetch('data/lezioni.json?v=20260915-lessons-pilot1',{cache:'no-store'});if(!r.ok)throw new Error('lezioni');LESSONS=await r.json();const count=LESSONS.subjects.reduce((n,s)=>n+(s.lessons?.length||0),0);document.getElementById('lessonCount').textContent=`${count} lezioni pilota`;renderSubjects();const q=new URLSearchParams(location.search).get('materia');if(q&&LESSONS.subjects.some(s=>s.id===q))openSubject(q)}catch(e){document.getElementById('subjectGrid').innerHTML='<div class="lesson-subject glass"><p>Impossibile caricare le lezioni.</p></div>'}}
function renderSubjects(){document.getElementById('subjectGrid').innerHTML=LESSONS.subjects.map(s=>{const active=s.status==='active'&&(s.lessons||[]).length>0;const done=(s.lessons||[]).filter(l=>lessonState(l.id).completed).length;const total=(s.lessons||[]).length;return `<article class="lesson-subject glass ${active?'active':''}" ${active?`onclick="openSubject('${esc(s.id)}')"`:''}><div><span class="badge">${active?'DISPONIBILE':'IN PREPARAZIONE'}</span><h3>${esc(s.name)}</h3><p>${esc(s.description)}</p></div><div class="lesson-subject-foot"><span class="muted">${active?`${done}/${total} completate`:'Prossimamente'}</span><button class="button ${active?'primary':'peach'}" ${active?'':'disabled'}>${active?'Apri percorso':'In preparazione'}</button></div></article>`}).join('')}
function subjectPercent(s){const lessons=s.lessons||[];if(!lessons.length)return 0;let sum=0;for(const l of lessons){const st=lessonState(l.id);if(st.completed){sum+=100;continue}const blocks=l.blocks?.length||1;sum+=Math.round((Math.min(st.block||0,blocks-1)/blocks)*100)}return Math.round(sum/lessons.length)}
function openSubject(id){const s=LESSONS.subjects.find(x=>x.id===id);if(!s||!s.lessons?.length)return;currentSubject=s;document.getElementById('lessonHome').classList.add('lesson-hidden');document.getElementById('runnerView').classList.add('lesson-hidden');document.getElementById('subjectView').classList.remove('lesson-hidden');document.getElementById('subjectCrumb').textContent=s.name;document.getElementById('subjectTitle').textContent=s.name.toUpperCase();document.getElementById('subjectDescription').textContent=s.description;renderLessonCards();updateSubjectProgress();window.scrollTo({top:0,behavior:'smooth'})}
function renderLessonCards(){const host=document.getElementById('lessonGrid');host.innerHTML=(currentSubject.lessons||[]).map((l,i)=>{const st=lessonState(l.id);const pct=st.completed?100:Math.round(((Math.min(st.block||0,(l.blocks?.length||1)-1))/(l.blocks?.length||1))*100);return `<article class="lesson-card glass active" onclick="openLesson('${esc(l.id)}')"><div><span class="badge">${st.completed?'COMPLETATA':st.block>0?'IN CORSO':'DA INIZIARE'}</span><h3>${String(i+1).padStart(2,'0')} · ${esc(l.title)}</h3><p>${esc(l.subtitle)}</p><div class="lesson-meta"><span>${esc(l.duration)}</span><span>${esc(l.sourcePages?'p. '+l.sourcePages:'')}</span></div></div><div><div class="lesson-progress"><div style="width:${pct}%"></div></div><div class="lesson-card-foot"><span class="muted">${pct}%</span><button class="button primary">${st.block>0&&!st.completed?'Continua':'Studia'}</button></div></div></article>`}).join('')}
function updateSubjectProgress(){const pct=subjectPercent(currentSubject);document.getElementById('subjectProgressBar').style.width=pct+'%';document.getElementById('subjectProgressText').textContent=pct+'%'}
function openLesson(id){const l=(currentSubject.lessons||[]).find(x=>x.id===id);if(!l)return;currentLesson=l;const st=lessonState(l.id);currentBlock=st.completed?0:Math.min(st.block||0,(l.blocks?.length||1)-1);document.getElementById('subjectView').classList.add('lesson-hidden');document.getElementById('runnerView').classList.remove('lesson-hidden');document.getElementById('runnerCrumb').textContent=l.title;document.getElementById('runnerTitle').textContent=l.title.toUpperCase();document.getElementById('runnerSubtitle').textContent=l.subtitle;document.getElementById('runnerSource').textContent=currentSubject.source||'Materiale del corso';document.getElementById('runnerPages').textContent=l.sourcePages?'Pagine '+l.sourcePages:'';const link=document.getElementById('runnerSourceLink');link.href=encodeURI(currentSubject.source||'#');renderBlock();window.scrollTo({top:0,behavior:'smooth'})}
function renderBlock(){const blocks=currentLesson.blocks||[];const b=blocks[currentBlock];if(!b)return;setLessonState(currentLesson.id,{block:Math.max(currentBlock,lessonState(currentLesson.id).block||0)});const host=document.getElementById('blockHost');if(b.type==='intro')host.innerHTML=`<section class="lesson-block block-intro"><h2>${esc(b.title)}</h2><p>${esc(b.text)}</p></section>`;else if(b.type==='text')host.innerHTML=`<section class="lesson-block"><h2>${esc(b.title)}</h2><p>${esc(b.text)}</p></section>`;else if(b.type==='key')host.innerHTML=`<section class="lesson-block block-key"><h2>${esc(b.title)}</h2><ul>${(b.items||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section>`;else if(b.type==='recall')host.innerHTML=`<section class="lesson-block block-recall"><div class="eyebrow">ACTIVE RECALL</div><h2>Prima prova a ricordare</h2><div class="recall-question">${esc(b.question)}</div><button class="button peach" style="margin-top:16px" onclick="revealRecall()">Mostra risposta</button><div id="recallAnswer" class="recall-answer">${esc(b.answer)}</div></section>`;else if(b.type==='checkpoint')renderCheckpoint(b);const pct=Math.round(((currentBlock+1)/blocks.length)*100);document.getElementById('runnerProgressBar').style.width=pct+'%';document.getElementById('runnerProgressText').textContent=`${currentBlock+1} di ${blocks.length} · ${pct}%`;document.getElementById('prevBlock').disabled=currentBlock===0;document.getElementById('nextBlock').textContent=currentBlock===blocks.length-1?'Completa lezione':'Continua'}
function revealRecall(){document.getElementById('recallAnswer')?.classList.add('show')}
function renderCheckpoint(b){const saved=lessonState(currentLesson.id).answers?.[currentBlock];document.getElementById('blockHost').innerHTML=`<section class="lesson-block block-checkpoint"><div class="eyebrow">CHECKPOINT</div><h2>${esc(b.question)}</h2><div id="checkpointOptions">${(b.options||[]).map((o,i)=>`<button class="checkpoint-option ${saved!==undefined?(i===b.correct?'correct':i===saved&&saved!==b.correct?'wrong':''):''}" onclick="answerCheckpoint(${i})" ${saved!==undefined?'disabled':''}><b>${String.fromCharCode(65+i)}.</b> ${esc(o)}</button>`).join('')}</div><div id="checkpointFeedback" class="checkpoint-feedback ${saved!==undefined?'show':''}">${saved!==undefined?esc(b.explanation):''}</div></section>`}
function answerCheckpoint(i){const b=currentLesson.blocks[currentBlock];const st=lessonState(currentLesson.id);const answers={...(st.answers||{}),[currentBlock]:i};setLessonState(currentLesson.id,{answers});document.querySelectorAll('.checkpoint-option').forEach((el,idx)=>{el.disabled=true;if(idx===b.correct)el.classList.add('correct');else if(idx===i)el.classList.add('wrong')});const f=document.getElementById('checkpointFeedback');f.textContent=(i===b.correct?'Corretto. ':'Da rivedere. ')+b.explanation;f.classList.add('show')}
function moveBlock(delta){const blocks=currentLesson.blocks||[];if(delta>0&&currentBlock===blocks.length-1){setLessonState(currentLesson.id,{block:blocks.length-1,completed:true});showToast('Lezione completata.');backToSubject();return}currentBlock=Math.max(0,Math.min(blocks.length-1,currentBlock+delta));renderBlock();window.scrollTo({top:0,behavior:'smooth'})}
function backToSubject(){if(!currentSubject)return;document.getElementById('runnerView').classList.add('lesson-hidden');document.getElementById('subjectView').classList.remove('lesson-hidden');renderLessonCards();updateSubjectProgress();window.scrollTo({top:0,behavior:'smooth'})}
function goHome(){document.getElementById('subjectView').classList.add('lesson-hidden');document.getElementById('runnerView').classList.add('lesson-hidden');document.getElementById('lessonHome').classList.remove('lesson-hidden');currentSubject=null;currentLesson=null;renderSubjects();window.scrollTo({top:0,behavior:'smooth'})}
function showToast(msg){const t=document.getElementById('lessonToast');t.textContent=msg;t.classList.add('show');clearTimeout(window._lessonToast);window._lessonToast=setTimeout(()=>t.classList.remove('show'),2200)}
init();