let LESSONS={exams:[]};let currentExam=null;let currentDiscipline=null;let currentLesson=null;let currentBlock=0;
const STORAGE_KEY='studyhub.lessons.progress.v1';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function loadProgress(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}catch(e){return {}}}
function saveProgress(p){localStorage.setItem(STORAGE_KEY,JSON.stringify(p))}
function lessonState(id){const p=loadProgress();return p[id]||{block:0,completed:false,answers:{},review:false}}
function setLessonState(id,patch){const p=loadProgress();p[id]={...lessonState(id),...patch};saveProgress(p)}
function disciplineLessons(d){return(d?.chapters||[]).flatMap(c=>c.lessons||[])}
function examLessons(e){return(e?.disciplines||[]).flatMap(d=>disciplineLessons(d))}
function chapterPercent(c){const ls=c.lessons||[];if(!ls.length)return 0;return Math.round(ls.reduce((n,l)=>n+lessonPercent(l),0)/ls.length)}
function lessonPercent(l){const st=lessonState(l.id);if(st.completed)return 100;const blocks=l.blocks?.length||1;return Math.round((Math.min(st.block||0,blocks-1)/blocks)*100)}
function disciplinePercent(d){const ls=disciplineLessons(d);if(!ls.length)return 0;return Math.round(ls.reduce((n,l)=>n+lessonPercent(l),0)/ls.length)}
function examPercent(e){const ls=examLessons(e);if(!ls.length)return 0;return Math.round(ls.reduce((n,l)=>n+lessonPercent(l),0)/ls.length)}
function answeredCount(l){return Object.keys(lessonState(l.id).answers||{}).length}
function correctCount(l){const st=lessonState(l.id);return(l.blocks||[]).reduce((n,b,i)=>n+(b.type==='checkpoint'&&st.answers?.[i]===b.correct?1:0),0)}
function checkpointCount(l){return(l.blocks||[]).filter(b=>b.type==='checkpoint').length}
function findLesson(d,id){for(const c of d?.chapters||[]){const l=(c.lessons||[]).find(x=>x.id===id);if(l)return l}return null}
function countChapters(){return LESSONS.exams.reduce((n,e)=>n+(e.disciplines||[]).reduce((m,d)=>m+(d.chapters?.length||0),0),0)}
function countLessons(){return LESSONS.exams.reduce((n,e)=>n+examLessons(e).length,0)}
async function init(){try{const r=await fetch('data/lezioni.json?v=20260915-lessons-pathways1',{cache:'no-store'});if(!r.ok)throw new Error('lezioni');LESSONS=await r.json();document.getElementById('examCount').textContent=`${LESSONS.exams.length} esami`;document.getElementById('chapterCount').textContent=`${countChapters()} capitoli`;document.getElementById('lessonCount').textContent=`${countLessons()} lezioni attive`;renderExams();const p=new URLSearchParams(location.search),examId=p.get('esame'),subjectId=p.get('materia');if(examId&&LESSONS.exams.some(e=>e.id===examId)){openExam(examId,false);if(subjectId&&currentExam?.disciplines?.some(d=>d.id===subjectId))openDiscipline(subjectId,false)}else if(subjectId&&LESSONS.exams.some(e=>e.id===subjectId))openExam(subjectId,false)}catch(e){document.getElementById('examGrid').innerHTML='<div class="lesson-subject glass"><p>Impossibile caricare le lezioni.</p></div>'}}
function renderExams(){const host=document.getElementById('examGrid');host.innerHTML=LESSONS.exams.map(e=>{const openable=(e.disciplines||[]).length>0;const lessons=examLessons(e),done=lessons.filter(l=>lessonState(l.id).completed).length,review=lessons.filter(l=>lessonState(l.id).review).length,chapters=(e.disciplines||[]).reduce((n,d)=>n+(d.chapters?.length||0),0);return `<article class="lesson-subject glass ${openable?'active':''}" ${openable?`onclick="openExam('${esc(e.id)}')"`:''}><div><span class="badge">${openable?'DISPONIBILE':'IN PREPARAZIONE'}</span><h3>${esc(e.name)}</h3><p>${esc(e.description)}</p></div><div class="exam-card-stats"><span>${e.disciplines?.length||0} materie</span><span>${chapters} capitoli</span>${lessons.length?`<span>${done}/${lessons.length} lezioni completate</span>`:''}${review?`<span>${review} da ripassare</span>`:''}</div><div class="lesson-subject-foot"><span class="muted">${openable?'Apri il percorso di studio':'Prossimamente'}</span><button class="button ${openable?'primary':'peach'}" ${openable?'':'disabled'}>${openable?'Apri esame':'In preparazione'}</button></div></article>`}).join('')}
function openExam(id,scroll=true){const e=LESSONS.exams.find(x=>x.id===id);if(!e||(e.disciplines||[]).length===0)return;currentExam=e;currentDiscipline=null;currentLesson=null;hideAll();document.getElementById('examView').classList.remove('lesson-hidden');document.getElementById('examCrumb').textContent=e.name;document.getElementById('examTitle').textContent=e.name.toUpperCase();document.getElementById('examDescription').textContent=e.description;renderDisciplines();updateExamProgress();if(scroll)window.scrollTo({top:0,behavior:'smooth'})}
function renderDisciplines(){const host=document.getElementById('disciplineGrid');host.innerHTML=(currentExam.disciplines||[]).map((d,i)=>{const ls=disciplineLessons(d),done=ls.filter(l=>lessonState(l.id).completed).length,review=ls.filter(l=>lessonState(l.id).review).length,pct=disciplinePercent(d),chapters=d.chapters?.length||0;return `<article class="discipline-card glass active" onclick="openDiscipline('${esc(d.id)}')"><div class="discipline-number">${String(i+1).padStart(2,'0')}</div><div><span class="badge">${ls.length?'LEZIONI ATTIVE':'STRUTTURA PRONTA'}</span><h3>${esc(d.name)}</h3><p>${esc(d.description)}</p></div><div class="discipline-meta"><span>${chapters} capitoli</span><span>${ls.length?`${done}/${ls.length} lezioni completate`:'Contenuti in preparazione'}</span>${review?`<span>${review} da ripassare</span>`:''}</div><div class="lesson-progress"><div style="width:${pct}%"></div></div><div class="lesson-subject-foot"><span class="muted">${ls.length?`${pct}% completato`:'Roadmap completa'}</span><button class="button ${ls.length?'primary':'peach'}">Apri materia</button></div></article>`}).join('')}
function updateExamProgress(){const pct=examPercent(currentExam),ls=examLessons(currentExam);document.getElementById('examProgressBar').style.width=pct+'%';document.getElementById('examProgressText').textContent=ls.length?`${pct}% · ${ls.filter(l=>lessonState(l.id).completed).length}/${ls.length} lezioni`:'0%'}
function openDiscipline(id,scroll=true){const d=(currentExam?.disciplines||[]).find(x=>x.id===id);if(!d)return;currentDiscipline=d;currentLesson=null;hideAll();document.getElementById('disciplineView').classList.remove('lesson-hidden');document.getElementById('disciplineExamBack').textContent=currentExam.name;document.getElementById('disciplineCrumb').textContent=d.name;document.getElementById('disciplineTitle').textContent=d.name.toUpperCase();document.getElementById('disciplineDescription').textContent=d.description;const source=document.getElementById('disciplineSourceLink'),sourceHref=d.sourceUrl||d.source||currentExam.materialsLink||'#';source.href=encodeURI(sourceHref);source.textContent=d.sourceActionLabel||(d.source?'Apri materiale originale':'Apri materiali');source.style.display=sourceHref&&sourceHref!=='#'?'inline-flex':'none';renderChapters();updateDisciplineProgress();if(scroll)window.scrollTo({top:0,behavior:'smooth'})}
function renderChapters(){const host=document.getElementById('chapterGrid');host.innerHTML=(currentDiscipline.chapters||[]).map((c,i)=>{const ls=c.lessons||[],pct=chapterPercent(c),done=ls.filter(l=>lessonState(l.id).completed).length,review=ls.filter(l=>lessonState(l.id).review).length;let status='IN PREPARAZIONE';if(ls.length)status=review?'DA RIPASSARE':done===ls.length?'COMPLETATO':'LEZIONE DISPONIBILE';const actions=ls.length?`<div class="chapter-lessons">${ls.map(l=>{const st=lessonState(l.id),checks=checkpointCount(l),score=answeredCount(l)&&checks?`${correctCount(l)}/${checks} checkpoint`:'';return `<button class="chapter-lesson-button" onclick="openLesson('${esc(l.id)}')"><span><b>${esc(l.title)}</b><small>${esc(l.duration||'')}${score?` · ${esc(score)}`:''}</small></span><strong>${st.completed?'Ripassa':st.block>0?'Continua':'Studia'} →</strong></button>`}).join('')}</div>`:`<div class="chapter-coming">Questo capitolo è già nella roadmap. La lezione interattiva verrà aggiunta senza cambiare la struttura.</div>`;return `<article class="chapter-card glass ${ls.length?'available':''}"><div class="chapter-index">${String(i+1).padStart(2,'0')}</div><div class="chapter-copy"><span class="badge">${status}</span><h3>${esc(c.title)}</h3><p>${esc(c.subtitle||'')}</p></div>${ls.length?`<div class="lesson-progress chapter-progress"><div style="width:${pct}%"></div></div>`:''}${actions}</article>`}).join('')}
function updateDisciplineProgress(){const pct=disciplinePercent(currentDiscipline),ls=disciplineLessons(currentDiscipline);document.getElementById('disciplineProgressBar').style.width=pct+'%';document.getElementById('disciplineProgressText').textContent=ls.length?`${pct}% · ${ls.filter(l=>lessonState(l.id).completed).length}/${ls.length} lezioni`:'Roadmap pronta'}
function openLesson(id){const l=findLesson(currentDiscipline,id);if(!l)return;currentLesson=l;const st=lessonState(l.id);currentBlock=st.completed?0:Math.min(st.block||0,(l.blocks?.length||1)-1);hideAll();document.getElementById('runnerView').classList.remove('lesson-hidden');document.getElementById('runnerExamCrumb').textContent=currentExam.name;document.getElementById('runnerDisciplineCrumb').textContent=currentDiscipline.name;document.getElementById('runnerCrumb').textContent=l.title;document.getElementById('runnerTitle').textContent=l.title.toUpperCase();document.getElementById('runnerSubtitle').textContent=l.subtitle;document.getElementById('runnerSource').textContent=l.sourceLabel||l.source||currentDiscipline.sourceLabel||currentDiscipline.source||'Materiale del corso';document.getElementById('runnerPages').textContent=l.sourcePages?'Pagine '+l.sourcePages:'';const runnerSourceLink=document.getElementById('runnerSourceLink'),runnerSourceHref=l.sourceUrl||currentDiscipline.sourceUrl||l.source||currentDiscipline.source||'#';runnerSourceLink.href=encodeURI(runnerSourceHref);runnerSourceLink.textContent=l.sourceActionLabel||currentDiscipline.sourceActionLabel||'Apri PDF originale';runnerSourceLink.style.display=runnerSourceHref&&runnerSourceHref!=='#'?'inline-flex':'none';document.getElementById('nextBlock').style.display='inline-flex';document.getElementById('prevBlock').style.display='inline-flex';updateReviewButton();renderBlock();window.scrollTo({top:0,behavior:'smooth'})}
function renderBlock(){const blocks=currentLesson.blocks||[],b=blocks[currentBlock];if(!b)return;setLessonState(currentLesson.id,{block:Math.max(currentBlock,lessonState(currentLesson.id).block||0)});const host=document.getElementById('blockHost');if(b.type==='intro')host.innerHTML=`<section class="lesson-block block-intro"><h2>${esc(b.title)}</h2><p>${esc(b.text)}</p></section>`;else if(b.type==='text')host.innerHTML=`<section class="lesson-block"><h2>${esc(b.title)}</h2><p>${esc(b.text)}</p></section>`;else if(b.type==='key')host.innerHTML=`<section class="lesson-block block-key"><h2>${esc(b.title)}</h2><ul>${(b.items||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section>`;else if(b.type==='recall')host.innerHTML=`<section class="lesson-block block-recall"><div class="eyebrow">ACTIVE RECALL</div><h2>Prima prova a ricordare</h2><div class="recall-question">${esc(b.question)}</div><button class="button peach" style="margin-top:16px" onclick="revealRecall()">Mostra risposta</button><div id="recallAnswer" class="recall-answer">${esc(b.answer)}</div></section>`;else if(b.type==='checkpoint')renderCheckpoint(b);const pct=Math.round(((currentBlock+1)/blocks.length)*100);document.getElementById('runnerProgressBar').style.width=pct+'%';document.getElementById('runnerProgressText').textContent=`${currentBlock+1} di ${blocks.length} · ${pct}%`;document.getElementById('prevBlock').disabled=currentBlock===0;const next=document.getElementById('nextBlock');next.textContent=currentBlock===blocks.length-1?'Completa lezione':'Continua';next.disabled=b.type==='checkpoint'&&lessonState(currentLesson.id).answers?.[currentBlock]===undefined}
function revealRecall(){document.getElementById('recallAnswer')?.classList.add('show')}
function renderCheckpoint(b){const saved=lessonState(currentLesson.id).answers?.[currentBlock];document.getElementById('blockHost').innerHTML=`<section class="lesson-block block-checkpoint"><div class="eyebrow">CHECKPOINT</div><h2>${esc(b.question)}</h2><div id="checkpointOptions">${(b.options||[]).map((o,i)=>`<button class="checkpoint-option ${saved!==undefined?(i===b.correct?'correct':i===saved&&saved!==b.correct?'wrong':''):''}" onclick="answerCheckpoint(${i})" ${saved!==undefined?'disabled':''}><b>${String.fromCharCode(65+i)}.</b> ${esc(o)}</button>`).join('')}</div><div id="checkpointFeedback" class="checkpoint-feedback ${saved!==undefined?'show':''}">${saved!==undefined?esc((saved===b.correct?'Corretto. ':'Da rivedere. ')+b.explanation):''}</div></section>`}
function answerCheckpoint(i){const b=currentLesson.blocks[currentBlock],st=lessonState(currentLesson.id),answers={...(st.answers||{}),[currentBlock]:i};setLessonState(currentLesson.id,{answers});document.querySelectorAll('.checkpoint-option').forEach((el,idx)=>{el.disabled=true;if(idx===b.correct)el.classList.add('correct');else if(idx===i)el.classList.add('wrong')});const f=document.getElementById('checkpointFeedback');f.textContent=(i===b.correct?'Corretto. ':'Da rivedere. ')+b.explanation;f.classList.add('show');document.getElementById('nextBlock').disabled=false}
function toggleReview(){if(!currentLesson)return;const st=lessonState(currentLesson.id);setLessonState(currentLesson.id,{review:!st.review});updateReviewButton();showToast(!st.review?'Segnata da ripassare.':'Rimossa dal ripasso.')}
function updateReviewButton(){const b=document.getElementById('reviewLesson');if(!b||!currentLesson)return;const on=lessonState(currentLesson.id).review;b.textContent=on?'✓ Da ripassare':'Segna da ripassare';b.classList.toggle('review-on',on)}
function moveBlock(delta){const blocks=currentLesson.blocks||[],b=blocks[currentBlock];if(delta>0&&b?.type==='checkpoint'&&lessonState(currentLesson.id).answers?.[currentBlock]===undefined){showToast('Rispondi al checkpoint prima di continuare.');return}if(delta>0&&currentBlock===blocks.length-1){setLessonState(currentLesson.id,{block:blocks.length-1,completed:true});showCompletion();return}currentBlock=Math.max(0,Math.min(blocks.length-1,currentBlock+delta));renderBlock();window.scrollTo({top:0,behavior:'smooth'})}
function showCompletion(){const checks=checkpointCount(currentLesson),right=correctCount(currentLesson),host=document.getElementById('blockHost'),sourceHref=currentLesson.sourceUrl||currentDiscipline.sourceUrl||currentLesson.source||currentDiscipline.source||'#',sourceAction=currentLesson.sourceActionLabel||currentDiscipline.sourceActionLabel||'Apri PDF originale';host.innerHTML=`<section class="lesson-complete"><div class="complete-mark">✓</div><div class="eyebrow">LEZIONE COMPLETATA</div><h2>${esc(currentLesson.title)}</h2><p>Hai completato il percorso${checks?` e risposto correttamente a <strong>${right}/${checks}</strong> checkpoint`:''}. Puoi ripassare il materiale originale, tornare ai capitoli oppure allenarti sull'esame.</p><div class="complete-actions">${currentExam.examLink?`<a class="button primary" href="${esc(currentExam.examLink)}">Allenati sul quiz</a>`:''}${sourceHref&&sourceHref!=='#'?`<a class="button peach" href="${esc(encodeURI(sourceHref))}" target="_blank">${esc(sourceAction)}</a>`:''}<button class="button terracotta" onclick="backToDiscipline()">Torna ai capitoli</button></div></section>`;document.getElementById('runnerProgressBar').style.width='100%';document.getElementById('runnerProgressText').textContent='Lezione completata · 100%';document.getElementById('prevBlock').disabled=true;document.getElementById('nextBlock').disabled=true;document.getElementById('nextBlock').style.display='none';document.getElementById('prevBlock').style.display='none';showToast('Lezione completata.')}
function hideAll(){['lessonHome','examView','disciplineView','runnerView'].forEach(id=>document.getElementById(id).classList.add('lesson-hidden'))}
function backToDiscipline(){if(!currentDiscipline)return;hideAll();document.getElementById('disciplineView').classList.remove('lesson-hidden');document.getElementById('nextBlock').style.display='inline-flex';document.getElementById('prevBlock').style.display='inline-flex';renderChapters();updateDisciplineProgress();window.scrollTo({top:0,behavior:'smooth'})}
function backToExam(){if(!currentExam)return;hideAll();document.getElementById('examView').classList.remove('lesson-hidden');renderDisciplines();updateExamProgress();window.scrollTo({top:0,behavior:'smooth'})}
function goHome(){hideAll();document.getElementById('lessonHome').classList.remove('lesson-hidden');currentExam=null;currentDiscipline=null;currentLesson=null;renderExams();window.scrollTo({top:0,behavior:'smooth'})}
function showToast(msg){const t=document.getElementById('lessonToast');t.textContent=msg;t.classList.add('show');clearTimeout(window._lessonToast);window._lessonToast=setTimeout(()=>t.classList.remove('show'),2200)}
init();