let CATALOG={subjects:[]};let currentFilter='Tutti';let currentSubject=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function init(){try{const r=await fetch('data/materiali.json?v=20260915-real-catalog-2',{cache:'no-store'});if(!r.ok)throw new Error('catalogo');CATALOG=await r.json();document.getElementById('subjectStat').textContent=`${CATALOG.subjects.length} materie`;const total=CATALOG.subjects.reduce((a,s)=>a+(s.documents?.length||0),0);const ready=CATALOG.subjects.reduce((a,s)=>a+(s.documents||[]).filter(d=>d.file).length,0);document.getElementById('docStat').textContent=`${ready} disponibili · ${total} catalogati`;renderSubjects()}catch(e){document.getElementById('subjectGrid').innerHTML='<div class="materials-empty glass">Impossibile caricare il catalogo materiali.</div>'}}
function setFilter(el){document.querySelectorAll('.materials-filter').forEach(x=>x.classList.remove('active'));el.classList.add('active');currentFilter=el.dataset.filter;renderSubjects()}
function renderSubjects(){const q=(document.getElementById('searchInput')?.value||'').trim().toLowerCase();const list=CATALOG.subjects.filter(s=>{const docs=s.documents||[];const filterOk=currentFilter==='Tutti'||docs.some(d=>d.type===currentFilter);const hay=[s.name,s.description,...(s.topics||[]),...docs.flatMap(d=>[d.title,d.sourceName,d.type])].join(' ').toLowerCase();return filterOk&&(!q||hay.includes(q))});document.getElementById('subjectGrid').innerHTML=list.length?list.map(s=>{const ready=(s.documents||[]).filter(d=>d.file).length;const total=(s.documents||[]).length;const badge=ready===total&&total?'DISPONIBILE':ready?'PARZIALMENTE DISPONIBILE':total?'CATALOGATO':'IN CATALOGAZIONE';return `<article class="materials-subject glass" onclick="openCourse('${esc(s.id)}')"><div><span class="badge">${badge}</span><h3>${esc(s.name)}</h3><p>${esc(s.description)}</p></div><div class="materials-subject-footer"><span class="materials-count">${ready} disponibili · ${total} catalogati</span><button class="button primary" type="button">Apri materia</button></div></article>`}).join(''):'<div class="materials-empty glass">Nessun materiale corrisponde alla ricerca.</div>'}
function openCourse(id){const s=CATALOG.subjects.find(x=>x.id===id);if(!s)return;currentSubject=s;document.getElementById('libraryView').classList.add('materials-hidden');document.getElementById('courseView').classList.remove('materials-hidden');document.getElementById('crumbCourse').textContent=s.name;document.getElementById('courseTitle').textContent=s.name.toUpperCase();document.getElementById('courseDescription').textContent=s.description+' Sbobine, compendi e slide vengono riuniti nello stesso spazio e organizzati per argomento.';document.getElementById('topicList').innerHTML=(s.topics||[]).map(t=>`<span class="materials-topic-chip">${esc(t)}</span>`).join('');renderDocs(s);window.scrollTo({top:0,behavior:'smooth'})}
function renderDocs(s){const docs=s.documents||[];document.getElementById('docGrid').innerHTML=docs.length?docs.map(d=>{const ready=!!d.file;const icon=d.type==='Slide'?'▧':d.type==='Sbobina'?'✎':'▤';return `<article class="materials-doc-card glass"><div class="materials-doc-top"><div><div class="materials-doc-type">${esc(d.type)}</div><h3>${esc(d.title)}</h3><p>${esc(d.meta||'PDF')}<br><span class="muted">File originale: ${esc(d.sourceName||'')}</span></p></div><div class="materials-doc-icon">${icon}</div></div>${ready?'':`<div class="materials-unavailable">Documento catalogato. Il PDF non risulta ancora pubblicato nel repository del sito.</div>`}<div class="materials-actions"><button class="button primary" ${ready?'':'disabled'} onclick="openReader('${esc(d.id)}')">Apri</button>${ready?`<a class="button peach" href="${esc(d.file)}" download>Scarica</a>`:`<button class="button peach" disabled>Scarica</button>`}</div></article>`}).join(''):'<div class="materials-empty glass">Nessun documento di questa materia è ancora stato catalogato nella biblioteca.</div>'}
function goLibrary(){document.getElementById('courseView').classList.add('materials-hidden');document.getElementById('libraryView').classList.remove('materials-hidden');window.scrollTo({top:0,behavior:'smooth'})}
function openReader(id){if(!currentSubject)return;const d=(currentSubject.documents||[]).find(x=>x.id===id);if(!d||!d.file){showToast('PDF non ancora pubblicato sul sito.');return}document.getElementById('readerTitle').textContent=d.title;document.getElementById('readerMeta').textContent=d.meta||'Documento PDF';document.getElementById('readerFrame').src=encodeURI(d.file);document.getElementById('readerDownload').href=encodeURI(d.file);document.getElementById('reader').classList.remove('materials-hidden');document.body.style.overflow='hidden'}
function closeReader(){document.getElementById('reader').classList.add('materials-hidden');document.getElementById('readerFrame').src='about:blank';document.body.style.overflow=''}
function showToast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window._mt);window._mt=setTimeout(()=>t.classList.remove('show'),2200)}
function shareApp(){const data={title:'Study Hub · Materiali',text:'Sbobine, compendi e slide su Study Hub',url:location.href};if(navigator.share)navigator.share(data).catch(()=>{});else navigator.clipboard?.writeText(location.href).then(()=>showToast('Link copiato negli appunti.'))}
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!document.getElementById('reader').classList.contains('materials-hidden'))closeReader()});init();